import type { Metadata } from "next";
import {
  cookie,
  roboto,
  azeret,
  inter,
  anek,
  syne,
  nunito,
  lato,
} from "./fonts";
import "./scss/globals.scss";
import Header from "@/components/header/Header";

export const metadata: Metadata = {
  title: "Gramtek",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.variable} ${cookie.variable} ${azeret.variable} ${inter.variable} ${anek.variable} ${syne.variable} ${nunito.variable} ${lato.variable}`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
